services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

volumes:
  db-data:
