services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: to-do-list
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/to-do-list?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

volumes:
  db-data:
